- hosts: 127.0.0.1
  become: true
  user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Make sure distro package of Docker is absent
      ansible.builtin.apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
          - docker-compose
        state: absent

    - name: Add docker apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/raspbian/gpg
        state: present

    - name: Get raspbian name
      ansible.builtin.command: lsb_release -cs
      register: raspbian_name
      changed_when: false

    - name: Add Docker repo
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        create: true
        line: "deb [arch=armhf] https://download.docker.com/linux/debian {{ raspbian_name.stdout }} stable"
        state: present
        owner: root
        group: root
        mode: 0644

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce:armhf
          - docker-ce-cli:armhf
          - docker-compose-plugin:armhf
        update_cache: true
        install_recommends: false

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        groups:
          - docker
          - adm
          - sudo
          - video
          - plugdev
          - users
          - input
          - netdev
          - gpio
          - dialout

    - name: Add a `veth` kernel module.
      ansible.builtin.shell: |
        sudo modprobe veth

    - name: Perform system upgrade
      ansible.builtin.apt:
        upgrade: dist
      tags:
        - system-upgrade

    - name: Clean up unused packages
      ansible.builtin.apt:
        autoremove: true
      tags:
        - system-upgrade
